export const TEXT = {
  common: {
    backToDashboard: '返回仪表板',
    loading: '加载中...',
    backToHome: '返回首页',
    processing: '处理中...',
    cancel: '取消',
    undo: '撤销',
    undoError: '撤销失败，请稍后重试'
  },
  auth: {
    emailRequired: '请输入邮箱',
    passwordRequired: '请输入密码',
    invalidEmail: '请输入有效的邮箱地址',
    invalidCredentials: '邮箱或密码错误',
    emailNotConfirmed: '请先验证邮箱后再登录',
    login: '登录',
    register: '注册',
    email: '邮箱',
    password: '密码',
    confirmPassword: '确认密码',
    loginButton: '登录',
    registerButton: '注册',
    loginError: '登录错误',
    registerError: '注册错误',
    passwordMismatch: '两次输入的密码不一致',
    hasAccount: '已有账号？',
    noAccount: '还没有账号？',
    loginLink: '立即登录',
    registerLink: '立即注册',
    confirmPasswordRequired: '请确认密码',
    registrationFailed: '注册失败，请稍后重试',
    emailAlreadyRegistered: '该邮箱已被注册',
    rateLimitExceeded: '操作太频繁，请稍后再试',
    logout: '退出登录',
    passwordTooShort: '密码长度至少为6位',
  },

  home: {
    title: '英语单词学习助手',
    description: '简单高效的英语单词学习工具，帮助你轻松掌握英语词汇',
  },
  dashboard: {
    title: '英语学习助手',
    overview: '总览',
    wordList: '单词列表',
    study: '开始学习',
    inputPlaceholder: '输入单词（用逗号或换行分隔）',
    submit: '提交',
    submitError: '提交失败',
    settings: {
      title: '设置',
      updateSuccess: '设置已更新',
      account: {
        title: '账户设置',
        description: '管理您的账户信息和安全设置',
        email: '邮箱',
        changePassword: '修改密码',
        currentPassword: '当前密码',
        newPassword: '新密码',
        confirmNewPassword: '确认新密码',
        currentPasswordError: '当前密码错误',
        updatePasswordError: '修改密码失败，请稍后重试',
        passwordUpdateSuccess: '密码修改成功',
      },
      preferences: {
        title: '学习偏好',
        description: '自定义您的学习目标和偏好',
        dailyGoal: '每日学习目标',
        updateError: '更新学习目标失败，请稍后重试',
        updateSuccess: '学习目标更新成功',
      },
      notifications: {
        title: '通知设置',
        description: '管理学习提醒和通知',
        dailyReminder: '每日学习提醒',
        dailyReminderDescription: '在设定时间提醒您完成每日学习目标',
        reminderTime: '提醒时间',
        updateError: '更新通知设置失败，请稍后重试',
        updateSuccess: '通知设置更新成功',
        permissionDenied: '请允许浏览器通知权限以启用提醒功能',
      },
    },
  },
}
